/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package edu.purdue.cs352.minijava.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_CLASS = 4;
  /** RegularExpression Id. */
  int KW_PUBLIC = 5;
  /** RegularExpression Id. */
  int KW_STATIC = 6;
  /** RegularExpression Id. */
  int KW_VOID = 7;
  /** RegularExpression Id. */
  int KW_MAIN = 8;
  /** RegularExpression Id. */
  int KW_STRING = 9;
  /** RegularExpression Id. */
  int KW_EXTENDS = 10;
  /** RegularExpression Id. */
  int KW_RETURN = 11;
  /** RegularExpression Id. */
  int KW_INT = 12;
  /** RegularExpression Id. */
  int KW_BOOLEAN = 13;
  /** RegularExpression Id. */
  int KW_IF = 14;
  /** RegularExpression Id. */
  int KW_ELSE = 15;
  /** RegularExpression Id. */
  int KW_WHILE = 16;
  /** RegularExpression Id. */
  int KW_TRUE = 17;
  /** RegularExpression Id. */
  int KW_FALSE = 18;
  /** RegularExpression Id. */
  int KW_THIS = 19;
  /** RegularExpression Id. */
  int KW_NEW = 20;
  /** RegularExpression Id. */
  int KW_PRINT = 21;
  /** RegularExpression Id. */
  int SYM_LBRACE = 22;
  /** RegularExpression Id. */
  int SYM_RBRACE = 23;
  /** RegularExpression Id. */
  int SYM_LPAREN = 24;
  /** RegularExpression Id. */
  int SYM_RPAREN = 25;
  /** RegularExpression Id. */
  int SYM_LBRACKET = 26;
  /** RegularExpression Id. */
  int SYM_RBRACKET = 27;
  /** RegularExpression Id. */
  int SYM_SEMICOLON = 28;
  /** RegularExpression Id. */
  int SYM_EQUAL = 29;
  /** RegularExpression Id. */
  int SYM_AND = 30;
  /** RegularExpression Id. */
  int SYM_OR = 31;
  /** RegularExpression Id. */
  int SYM_LESS = 32;
  /** RegularExpression Id. */
  int SYM_LESS_EQUAL = 33;
  /** RegularExpression Id. */
  int SYM_EQUALS = 34;
  /** RegularExpression Id. */
  int SYM_NOT_EQUALS = 35;
  /** RegularExpression Id. */
  int SYM_GREATER = 36;
  /** RegularExpression Id. */
  int SYM_GREATER_EQUALS = 37;
  /** RegularExpression Id. */
  int SYM_PLUS = 38;
  /** RegularExpression Id. */
  int SYM_MINUS = 39;
  /** RegularExpression Id. */
  int SYM_MULTIPLY = 40;
  /** RegularExpression Id. */
  int SYM_DIVIDE = 41;
  /** RegularExpression Id. */
  int SYM_MOD = 42;
  /** RegularExpression Id. */
  int SYM_NOT = 43;
  /** RegularExpression Id. */
  int SYM_DOT = 44;
  /** RegularExpression Id. */
  int SYM_COMMA = 45;
  /** RegularExpression Id. */
  int IDENTIFIER = 46;
  /** RegularExpression Id. */
  int INT_LITERAL = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"System.out.println\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\".\"",
    "\",\"",
    "<IDENTIFIER>",
    "<INT_LITERAL>",
  };

}
